### ISSUE TITLE
arm64: Fatal TYPE-ERROR: The value 64 is not of type (INTEGER -32 63)

### ISSUE THREAD

**Issue by dimitri** [froydnj/ironclad#76]
Please see details at https://github.com/dimitri/pgloader/issues/490. What can we do about it?

**Comment by froydnj** [comment]
Thanks for the report.

@glv2 I think this is due to:

https://github.com/froydnj/ironclad/blob/master/src/digests/skein.lisp#L182

since a 0-bit field doesn't make a whole lot of sense.  Is that supposed to be `(ldb 32 0 (aref tweak 1))` or `(ldb 32 32 (aref tweak 1))`?

**Comment by glv2** [comment]
Indeed the arguments of the call to *byte* are in the wrong order.
Fixed in PR #78

**Comment by ChristophBerg** [comment]
Fwiw, #78 doesn't fix the original problem, I'm still getting the same TYPE-ERROR with ironclad updated to HEAD.

**Comment by froydnj** [comment]
@ChristophBerg thanks for checking.  We'll need more details about the error, such as a backtrace for where the error, then; I don't have an arm64 machine to test on.

**Comment by glv2** [comment]
@ChristophBerg if you have the possibility it could be useful to compile the following functions in the REPL of SBCL on the arm64 machine, in order to be sure that there isn't a bug when SBCL generates optimized assembly for arm64:

``` lisp
(defun foo (n)
  (declare (type (unsigned-byte 64) n)
           (optimize (speed 3) (space 0) (debug 0) (safety 0)))
  (ldb (byte 32 0) n))

(defun foz (n x)
  (declare (type (unsigned-byte 64) n)
           (type (unsigned-byte 32) x)
           (optimize (speed 3) (space 0) (debug 0) (safety 0)))
  (let ((r n))
    (declare (type (unsigned-byte 64) r))
    (setf (ldb (byte 32 0) r) x)
    r))

(defun bar (n)
  (declare (type (unsigned-byte 64) n)
           (optimize (speed 3) (space 0) (debug 0) (safety 0)))
  (ldb (byte 32 32) n))

(defun baz (n x)
  (declare (type (unsigned-byte 64) n)
           (type (unsigned-byte 32) x)
           (optimize (speed 3) (space 0) (debug 0) (safety 0)))
  (let ((r n))
    (declare (type (unsigned-byte 64) r))
    (setf (ldb (byte 32 32) r) x)
    r))
```

**Comment by ChristophBerg** [comment]
They seem to compile fine, i.e. sbcl doesn't complain. Do you want the result in some form? (I'm afraid I need detailed instructions, my only experience with CL so far is making sure dim's pgloader compiles on Debian.)

**Comment by glv2** [comment]
Can you enter the following in the REPL:

``` lisp
(declaim (ftype (function ((unsigned-byte 64) (unsigned-byte 64)) (unsigned-byte 64)) mod64+))
(defun mod64+ (a b)
  (declare (type (unsigned-byte 64) a b))
  (ldb (byte 64 0) (+ a b)))

(defun skein-increment-counter (tweak n)
  (declare (type (simple-array (unsigned-byte 64) (2)) tweak)
           (type (unsigned-byte 32) n)
           (optimize (speed 3) (space 0) (debug 0) (safety 0)))
  (let ((x (ldb (byte 32 0) (aref tweak 0)))
        (y (ldb (byte 32 32) (aref tweak 0)))
        (z (ldb (byte 32 0) (aref tweak 1))))
    (declare (type (unsigned-byte 64) x y z))
    (setf x (mod64+ x n)
          y (mod64+ y (ldb (byte 32 32) x))
          z (mod64+ z (ldb (byte 32 32) y)))
    (setf (ldb (byte 32 0) (aref tweak 0)) (ldb (byte 32 0) x)
          (ldb (byte 32 32) (aref tweak 0)) (ldb (byte 32 0) y))
    (setf (ldb (byte 32 0) (aref tweak 1)) (ldb (byte 32 0) z))
    (values)))
```

In theory the ```skein-increment-counter``` function should fail to compile as it does in the log file at https://github.com/dimitri/pgloader/issues/490. When the error message appears, enter ```backtrace``` to get the call stack,  and paste it here.

In case it compiles without error (for some reason), enter the following in the REPL:

``` lisp
(let ((tweak (make-array 2 :element-type '(unsigned-byte 64) :initial-element #xffffffffffffffff)))
  (skein-increment-counter tweak 50)
  (assert (= (aref tweak 0) 49))
  (assert (= (aref tweak 1) #xffffffff00000000))
  t)
```

It should print ```T``` if the result is correct and throw an error otherwise.

**Comment by ChristophBerg** [comment]
This doesn't seem to help:
```
This is SBCL 1.3.11.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (declaim (ftype (function ((unsigned-byte 64) (unsigned-byte 64)) (unsigned-byte 64)) mod64+))
(defun mod64+ (a b)
  (declare (type (unsigned-byte 64) a b))
  (ldb (byte 64 0) (+ a b)))
(MOD64+)
* (defun skein-increment-counter (tweak n)
  (declare (type (simple-array (unsigned-byte 64) (2)) tweak)
           (type (unsigned-byte 32) n)
           (optimize (speed 3) (space 0) (debug 0) (safety 0)))
  (let ((x (ldb (byte 32 0) (aref tweak 0)))
    
MOD64+
*     (y (ldb (byte 32 32) (aref tweak 0)))
        (z (ldb (byte 32 0) (aref tweak 1))))
    (declare (type (unsigned-byte 64) x y z))
    (setf x (mod64+ x n)
          y (mod64+ y (ldb (byte 32 32) x))
          z (mod64+ z (ldb (byte 32 32) y)))
    (setf (ldb (byte 32 0) (aref tweak 0)) (ldb (byte 32 0) x)
          (ldb (byte 32 32) (aref tweak 0)) (ldb (byte 32 0) y))
    (setf (ldb (byte 32 0) (aref tweak 1)) (ldb (byte 32 0) z))
    (values)))

SKEIN-INCREMENT-COUNTER
* (let ((tweak (make-array 2 :element-type '(unsigned-byte 64) :initial-element #xffffffffffffffff)))
  (skein-increment-counter tweak 50)
  (assert (= (aref tweak 0) 49))
  (assert (= (aref tweak 1) #xffffffff00000000))
  t)

T
*
```

**Comment by glv2** [comment]
Ok, that's strange... Let's try to reproduce the error by compiling a file.

First, write the three previous forms (```(declaim...)```, ```(defun mod64+...)``` and ```(defun skein-increment-counter...)```) to a file named *foo.lisp*.

Then enter the following in the REPL:
``` lisp
(compile-file "foo.lisp")
```

If the error occurs, enter ```backtrace``` and copy the result here.

If the error does not occur, try to compile *ironclad* like in https://github.com/dimitri/pgloader/issues/490 with ```(asdf:load-system :ironclad)``` and enter ```backtrace``` after the *type-error* occurs.

**Comment by ChristophBerg** [comment]
The error did not occur.

I was only able to compile ironclad in the version currently in Debian unstable (0.33.0-53-gf5d1699-1). The output is:

``` lisp
(require :asdf)
(asdf:load-system :ironclad)
...
; /home/myon/.cache/common-lisp/sbcl-1.3.11.debian-linux-arm64/usr/share/common-lisp/source/ironclad/src/digests/whirlpool-tmpZE69DN33.fasl written
; compilation finished in 0:00:02.930
; compiling file "/usr/share/common-lisp/source/ironclad/src/digests/tree-hash.lisp" (written 22 NOV 2016 09:17:20 PM):
; compiling (IN-PACKAGE :CRYPTO)
; compiling (DEFPARAMETER *LEAF-BYTE* ...)
; compiling (DEFPARAMETER *INTERNAL-BYTE* ...)
; compiling (DEFUN MAKE-TREE-HASH-LEAF-DIGEST ...)
; compiling (DEFSTRUCT (TREE-HASH # ...) ...)
; compiling (DEFUN %MAKE-TREE-HASH-DIGEST ...)
; compiling (DEFUN MAKE-TIGER-TREE-HASH ...)
; compiling (DEFMETHOD BLOCK-LENGTH ...)
; compiling (DEFMETHOD DIGEST-LENGTH ...)
; compiling (DEFMETHOD REINITIALIZE-INSTANCE ...)
; compiling (DEFMETHOD COPY-DIGEST ...)
; compiling (DEFINE-DIGEST-UPDATER TREE-HASH ...)
; compiling (DEFUN UPDATE-TREE-HASH-BRANCH ...)
; compiling (DEFUN MERGE-TREE-HASH-BRANCH ...)
; compiling (DEFUN COMBINE-HASH-TREE-DIGESTS ...)
; compiling (DEFMETHOD PRODUCE-DIGEST ...)
; compiling (SETF (GET # ...) ...)
; compiling (SETF (GET # ...) ...)

; /home/myon/.cache/common-lisp/sbcl-1.3.11.debian-linux-arm64/usr/share/common-lisp/source/ironclad/src/digests/tree-hash-tmpG8099TO3.fasl written
; compilation finished in 0:00:00.246
; compiling file "/usr/share/common-lisp/source/ironclad/src/digests/skein.lisp" (written 22 NOV 2016 09:17:20 PM):
; compiling (IN-PACKAGE :CRYPTO)
; compiling (DEFCONSTANT +SKEIN-KEY+ ...)
; compiling (DEFCONSTANT +SKEIN-CFG+ ...)
; compiling (DEFCONSTANT +SKEIN-PRS+ ...)
; compiling (DEFCONSTANT +SKEIN-PK+ ...)
; compiling (DEFCONSTANT +SKEIN-KDF+ ...)
; compiling (DEFCONSTANT +SKEIN-NON+ ...)
; compiling (DEFCONSTANT +SKEIN-MSG+ ...)
; compiling (DEFCONSTANT +SKEIN-OUT+ ...)
; compiling (DECLAIM (TYPE # ...))
; compiling (DECLAIM (TYPE # ...))
; compiling (DECLAIM (TYPE # ...))
; compiling (DEFCONST +SKEIN256-IV-128+ ...)
; compiling (DEFCONST +SKEIN256-IV-160+ ...)
; compiling (DEFCONST +SKEIN256-IV-224+ ...)
; compiling (DEFCONST +SKEIN256-IV-256+ ...)
; compiling (DEFCONST +SKEIN512-IV-128+ ...)
; compiling (DEFCONST +SKEIN512-IV-160+ ...)
; compiling (DEFCONST +SKEIN512-IV-224+ ...)
; compiling (DEFCONST +SKEIN512-IV-256+ ...)
; compiling (DEFCONST +SKEIN512-IV-384+ ...)
; compiling (DEFCONST +SKEIN512-IV-512+ ...)
; compiling (DEFCONST +SKEIN1024-IV-384+ ...)
; compiling (DEFCONST +SKEIN1024-IV-512+ ...)
; compiling (DEFCONST +SKEIN1024-IV-1024+ ...)
; compiling (DEFUN SKEIN-GET-IV ...)
; compiling (DEFUN SKEIN-INCREMENT-COUNTER ...)
debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1003C0C2A3}>:
  The value
    64
  is not of type
    (INTEGER -32 63)

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "digests" "skein">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "digests" "skein">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Exit debugger, returning to top level.

(SB-ARM64-ASM::EMIT-BITFIELD #<SB-ASSEM:SEGMENT :TYPE :REGULAR> 1 2 1 33 64 4 1) [tl,external]
0] backtrace

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1003C0C2A3}>
0: (SB-ARM64-ASM::EMIT-BITFIELD #<SB-ASSEM:SEGMENT :TYPE :REGULAR> 1 2 1 33 64 4 1) [tl,external]
1: (SB-ARM64-ASM::|ubfm| #<SB-ASSEM:SEGMENT :TYPE :REGULAR> #<SB-C::VOP :INFO SB-VM::LDB-C/FIXNUM :ARGS #<SB-C:TN-REF :TN #<SB-C:TN Y!1[NL4]> :WRITE-P NIL :VOP SB-VM::LDB-C/FIXNUM> :RESULTS #<SB-C:TN-REF :TN #<SB-C:TN t2[NL1]> :WRITE-P T :VOP SB-VM::LDB-C/FIXNUM> :CODEGEN-INFO (32 32)> #<SB-C:TN t2[NL1]> #<SB-C:TN Y!1[NL4]> 33 64)
2: ((SB-C::VOP SB-VM::LDB-C/FIXNUM) #<SB-C::VOP :INFO SB-VM::LDB-C/FIXNUM :ARGS #<SB-C:TN-REF :TN #<SB-C:TN Y!1[NL4]> :WRITE-P NIL :VOP SB-VM::LDB-C/FIXNUM> :RESULTS #<SB-C:TN-REF :TN #<SB-C:TN t2[NL1]> :WRITE-P T :VOP SB-VM::LDB-C/FIXNUM> :CODEGEN-INFO (32 32)>)
3: (SB-C::GENERATE-CODE #<SB-C:COMPONENT :NAME SKEIN-INCREMENT-COUNTER {10048C6813}>)
4: (SB-C::%COMPILE-COMPONENT #<SB-C:COMPONENT :NAME SKEIN-INCREMENT-COUNTER {10048C6813}>)
5: (SB-C::COMPILE-COMPONENT #<SB-C:COMPONENT :NAME SKEIN-INCREMENT-COUNTER {10048C6813}>)
6: (SB-C::%COMPILE (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY (UNSIGNED-BYTE 64) (2)) TWEAK) (TYPE (UNSIGNED-BYTE 64) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (BLOCK SKEIN-INCREMENT-COUNTER (LET ((X #) (Y #) (Z #)) (DECLARE (TYPE # X Y Z)) (SETF X (MOD64+ X N) Y (MOD64+ Y #) Z (MOD64+ Z #)) (SETF (LDB # #) (LDB # X) (LDB # #) (LDB # Y)) (SETF (LDB # #) (LDB # Z)) (VALUES)))) #<SB-FASL:FASL-OUTPUT "/home/myon/.cache/common-lisp/sbcl-1.3.11.debian-linux-arm64/usr/share/common-lisp/source/ironclad/src/digests/skein-tmpTASQCYAW.fasl"> :NAME NIL :PATH ((FUNCTION #1=(SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE # TWEAK) (TYPE # N) (OPTIMIZE # # # # #)) (BLOCK SKEIN-INCREMENT-COUNTER (LET # # # # # #)))) #1# #2=(SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) #1# (SB-C:SOURCE-LOCATION)) #2# (PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) #2#) SB-C::ORIGINAL-SOURCE-START 0 26))
7: (SB-C::FOPCOMPILE-FUNCTION #<SB-FASL:FASL-OUTPUT "/home/myon/.cache/common-lisp/sbcl-1.3.11.debian-linux-arm64/usr/share/common-lisp/source/ironclad/src/digests/skein-tmpTASQCYAW.fasl"> (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY (UNSIGNED-BYTE 64) (2)) TWEAK) (TYPE (UNSIGNED-BYTE 64) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (BLOCK SKEIN-INCREMENT-COUNTER (LET ((X #) (Y #) (Z #)) (DECLARE (TYPE # X Y Z)) (SETF X (MOD64+ X N) Y (MOD64+ Y #) Z (MOD64+ Z #)) (SETF (LDB # #) (LDB # X) (LDB # #) (LDB # Y)) (SETF (LDB # #) (LDB # Z)) (VALUES)))) ((FUNCTION #1=(SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE # TWEAK) (TYPE # N) (OPTIMIZE # # # # #)) (BLOCK SKEIN-INCREMENT-COUNTER (LET # # # # # #)))) #1# #2=(SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) #1# (SB-C:SOURCE-LOCATION)) #2# (PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) #2#) SB-C::ORIGINAL-SOURCE-START 0 26) T)
8: (SB-C::FOPCOMPILE (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY # #) TWEAK) (TYPE (UNSIGNED-BYTE 64) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (BLOCK SKEIN-INCREMENT-COUNTER (LET (# # #) (DECLARE #) (SETF X # Y # Z #) (SETF # # # #) (SETF # #) (VALUES)))) (SB-C:SOURCE-LOCATION)) (#1=(SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE # TWEAK) (TYPE # N) (OPTIMIZE # # # # #)) (BLOCK SKEIN-INCREMENT-COUNTER (LET # # # # # #))) (SB-C:SOURCE-LOCATION)) (PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) #1#) SB-C::ORIGINAL-SOURCE-START 0 26) NIL NIL)
9: (SB-C::CONVERT-AND-MAYBE-COMPILE (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY # #) TWEAK) (TYPE (UNSIGNED-BYTE 64) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (BLOCK SKEIN-INCREMENT-COUNTER (LET (# # #) (DECLARE #) (SETF X # Y # Z #) (SETF # # # #) (SETF # #) (VALUES)))) (SB-C:SOURCE-LOCATION)) (#1=(SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE # TWEAK) (TYPE # N) (OPTIMIZE # # # # #)) (BLOCK SKEIN-INCREMENT-COUNTER (LET # # # # # #))) (SB-C:SOURCE-LOCATION)) (PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) #1#) SB-C::ORIGINAL-SOURCE-START 0 26) NIL)
10: ((FLET SB-C::DEFAULT-PROCESSOR :IN SB-C::PROCESS-TOPLEVEL-FORM) (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY # #) TWEAK) (TYPE (UNSIGNED-BYTE 64) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (BLOCK SKEIN-INCREMENT-COUNTER (LET (# # #) (DECLARE #) (SETF X # Y # Z #) (SETF # # # #) (SETF # #) (VALUES)))) (SB-C:SOURCE-LOCATION)))
11: (SB-C::PROCESS-TOPLEVEL-FORM (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY # #) TWEAK) (TYPE (UNSIGNED-BYTE 64) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (BLOCK SKEIN-INCREMENT-COUNTER (LET (# # #) (DECLARE #) (SETF X # Y # Z #) (SETF # # # #) (SETF # #) (VALUES)))) (SB-C:SOURCE-LOCATION)) ((PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE # # #) (BLOCK SKEIN-INCREMENT-COUNTER #)) (SB-C:SOURCE-LOCATION))) SB-C::ORIGINAL-SOURCE-START 0 26) NIL)
12: (SB-C::PROCESS-TOPLEVEL-PROGN ((EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE # TWEAK) (TYPE # N) (OPTIMIZE # # # # #)) (BLOCK SKEIN-INCREMENT-COUNTER (LET # # # # # #))) (SB-C:SOURCE-LOCATION))) ((PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE # # #) (BLOCK SKEIN-INCREMENT-COUNTER #)) (SB-C:SOURCE-LOCATION))) SB-C::ORIGINAL-SOURCE-START 0 26) NIL)
13: (SB-C::PROCESS-TOPLEVEL-FORM (PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE # TWEAK) (TYPE # N) (OPTIMIZE # # # # #)) (BLOCK SKEIN-INCREMENT-COUNTER (LET # # # # # #))) (SB-C:SOURCE-LOCATION))) (SB-C::ORIGINAL-SOURCE-START 0 26) NIL)
14: ((FLET SB-C::DEFAULT-PROCESSOR :IN SB-C::PROCESS-TOPLEVEL-FORM) (DEFUN SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY (UNSIGNED-BYTE 64) (2)) TWEAK) (TYPE (UNSIGNED-BYTE 64) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (LET ((X (LDB # #)) (Y (LDB # #)) (Z (LDB # #))) (DECLARE (TYPE (UNSIGNED-BYTE 64) X Y Z)) (SETF X (MOD64+ X N) Y (MOD64+ Y (LDB # X)) Z (MOD64+ Z (LDB # Y))) (SETF (LDB (BYTE 32 0) (AREF TWEAK 0)) (LDB (BYTE 32 0) X) (LDB (BYTE 32 32) (AREF TWEAK 0)) (LDB (BYTE 32 0) Y)) (SETF (LDB (BYTE 0 32) (AREF TWEAK 1)) (LDB (BYTE 32 0) Z)) (VALUES))))
15: (SB-C::PROCESS-TOPLEVEL-FORM (DEFUN SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY (UNSIGNED-BYTE 64) (2)) TWEAK) (TYPE (UNSIGNED-BYTE 64) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (LET ((X (LDB # #)) (Y (LDB # #)) (Z (LDB # #))) (DECLARE (TYPE (UNSIGNED-BYTE 64) X Y Z)) (SETF X (MOD64+ X N) Y (MOD64+ Y (LDB # X)) Z (MOD64+ Z (LDB # Y))) (SETF (LDB (BYTE 32 0) (AREF TWEAK 0)) (LDB (BYTE 32 0) X) (LDB (BYTE 32 32) (AREF TWEAK 0)) (LDB (BYTE 32 0) Y)) (SETF (LDB (BYTE 0 32) (AREF TWEAK 1)) (LDB (BYTE 32 0) Z)) (VALUES))) (SB-C::ORIGINAL-SOURCE-START 0 26) NIL)
16: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-C::SUB-SUB-COMPILE-FILE) (DEFUN SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY (UNSIGNED-BYTE 64) (2)) TWEAK) (TYPE (UNSIGNED-BYTE 64) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (LET ((X (LDB # #)) (Y (LDB # #)) (Z (LDB # #))) (DECLARE (TYPE (UNSIGNED-BYTE 64) X Y Z)) (SETF X (MOD64+ X N) Y (MOD64+ Y (LDB # X)) Z (MOD64+ Z (LDB # Y))) (SETF (LDB (BYTE 32 0) (AREF TWEAK 0)) (LDB (BYTE 32 0) X) (LDB (BYTE 32 32) (AREF TWEAK 0)) (LDB (BYTE 32 0) Y)) (SETF (LDB (BYTE 0 32) (AREF TWEAK 1)) (LDB (BYTE 32 0) Z)) (VALUES))) :CURRENT-INDEX 26)
17: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-C::SUB-SUB-COMPILE-FILE) {100250A58B}> #<SB-C::SOURCE-INFO {1003705613}> SB-C::INPUT-ERROR-IN-COMPILE-FILE)
18: (SB-C::SUB-SUB-COMPILE-FILE #<SB-C::SOURCE-INFO {1003705613}>)
19: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-C::SUB-COMPILE-FILE))
20: ((FLET #:WITHOUT-INTERRUPTS-BODY-375 :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
21: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-C::SUB-COMPILE-FILE) {7F9EE44ABB}> #<SB-THREAD:MUTEX "World Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {1003C0C2A3}>> T NIL)
22: ((LAMBDA NIL :IN SB-C::SUB-COMPILE-FILE))
23: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
24: (SB-C::SUB-COMPILE-FILE #<SB-C::SOURCE-INFO {1003705613}>)
25: (COMPILE-FILE #P"/usr/share/common-lisp/source/ironclad/src/digests/skein.lisp" :OUTPUT-FILE #P"/home/myon/.cache/common-lisp/sbcl-1.3.11.debian-linux-arm64/usr/share/common-lisp/source/ironclad/src/digests/skein-tmpTASQCYAW.fasl" :VERBOSE NIL :PRINT NIL :EXTERNAL-FORMAT :UTF-8 :TRACE-FILE NIL :BLOCK-COMPILE NIL :EMIT-CFASL NIL)
26: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<CLOSURE (LAMBDA NIL :IN UIOP/LISP-BUILD:COMPILE-FILE*) {1003702D9B}> NIL)
27: (UIOP/PATHNAME:CALL-WITH-ENOUGH-PATHNAME #P"/usr/share/common-lisp/source/ironclad/src/digests/skein.lisp" NIL #<CLOSURE (LAMBDA (UIOP/LISP-BUILD::INPUT-FILE) :IN UIOP/LISP-BUILD:COMPILE-FILE*) {1003702D1B}>)
28: (UIOP/LISP-BUILD:COMPILE-FILE* #P"/usr/share/common-lisp/source/ironclad/src/digests/skein.lisp" :OUTPUT-FILE #P"/home/myon/.cache/common-lisp/sbcl-1.3.11.debian-linux-arm64/usr/share/common-lisp/source/ironclad/src/digests/skein.fasl" :EXTERNAL-FORMAT :UTF-8 :WARNINGS-FILE NIL)
29: (ASDF/LISP-ACTION:PERFORM-LISP-COMPILATION #<ASDF/LISP-ACTION:COMPILE-OP > #<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE "ironclad" "src" "digests" "skein">)
30: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unavailable argument> #<unavailable argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE "ironclad" "src" "digests" "skein">)
31: ((:METHOD ASDF/ACTION:PERFORM :AROUND (ASDF/LISP-ACTION:COMPILE-OP IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE)) #<ASDF/LISP-ACTION:COMPILE-OP > #<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE "ironclad" "src" "digests" "skein">) [fast-method]
32: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE "ironclad" "src" "digests" "skein">) [fast-method]
33: ((:METHOD ASDF/PLAN:PERFORM-PLAN (LIST)) ((#1=#<ASDF/LISP-ACTION:PREPARE-OP > . #2=#<ASDF/OPERATE:REQUIRE-SYSTEM "sb-rotate-byte">) (#3=#<ASDF/LISP-ACTION:COMPILE-OP > . #2#) (#4=#<ASDF/LISP-ACTION:LOAD-OP > . #2#) (#1# . #5=#<ASDF/OPERATE:REQUIRE-SYSTEM "sb-posix">) (#3# . #5#) (#4# . #5#) (#1# . #<ASDF/SYSTEM:SYSTEM #6="nibbles">) (#1# . #7=#<ASDF/COMPONENT:STATIC-FILE #6# "README">) (#3# . #7#) (#4# . #7#) (#1# . #8=#<ASDF/COMPONENT:STATIC-FILE #6# "LICENSE">) (#3# . #8#) ...) :FORCE NIL) [fast-method]
34: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
35: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) ((#1=#<ASDF/LISP-ACTION:PREPARE-OP > . #2=#<ASDF/OPERATE:REQUIRE-SYSTEM "sb-rotate-byte">) (#3=#<ASDF/LISP-ACTION:COMPILE-OP > . #2#) (#4=#<ASDF/LISP-ACTION:LOAD-OP > . #2#) (#1# . #5=#<ASDF/OPERATE:REQUIRE-SYSTEM "sb-posix">) (#3# . #5#) (#4# . #5#) (#1# . #<ASDF/SYSTEM:SYSTEM #6="nibbles">) (#1# . #7=#<ASDF/COMPONENT:STATIC-FILE #6# "README">) (#3# . #7#) (#4# . #7#) (#1# . #8=#<ASDF/COMPONENT:STATIC-FILE #6# "LICENSE">) (#3# . #8#) ...)) [fast-method]
36: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
37: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1003BFA3F3}>) [fast-method]
38: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "ironclad">) [fast-method]
39: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "ironclad">)
40: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
41: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "ironclad">) [fast-method]
42: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP :IRONCLAD)
43: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
44: (ASDF/CACHE:CALL-WITH-ASDF-CACHE #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1003BF651B}> :OVERRIDE NIL :KEY NIL)
45: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :IRONCLAD) [fast-method]
46: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :IRONCLAD) [fast-method]
47: (ASDF/OPERATE:LOAD-SYSTEM :IRONCLAD)
48: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/OPERATE:LOAD-SYSTEM :IRONCLAD) #<NULL-LEXENV>)
49: (EVAL (ASDF/OPERATE:LOAD-SYSTEM :IRONCLAD))
50: (SB-EXT:INTERACTIVE-EVAL (ASDF/OPERATE:LOAD-SYSTEM :IRONCLAD) :EVAL NIL)
51: (SB-IMPL::REPL-FUN NIL)
52: ((LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL))
53: (SB-IMPL::%WITH-REBOUND-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL) {1003BF220B}>)
54: (SB-IMPL::TOPLEVEL-REPL NIL)
55: (SB-IMPL::TOPLEVEL-INIT)
56: ((FLET #:WITHOUT-INTERRUPTS-BODY-86 :IN SB-EXT:SAVE-LISP-AND-DIE))
57: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

0] 
```

What would I need to do to compile ironclad from git?

**Comment by glv2** [comment]
To compile ironclad from git, download https://github.com/froydnj/ironclad/archive/master.zip and extract it somewhere. Then in the REPL enter:
``` lisp
(push "/the/path/where/you/put/the/sources/" asdf:*central-registry*)
(asdf:load-system :ironclad)
```
If it compiles without error, it would mean that the patch of commit 0f2e90fdaa8eede0630418d3bd7c55ca46df0d94 works, and in that case updating the version of ironclad in debian should solve the problem for pgloader.
If it fails to compile, you can get the backtrace and paste it here to see if there's a difference with the backtrace of the previous version.

**Comment by ChristophBerg** [comment]
Still the same error - the backtrace is slightly different. (wdiff works much better than diff on it)

``` lisp
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10030982A3}>
0: (SB-ARM64-ASM::EMIT-BITFIELD #<SB-ASSEM:SEGMENT :TYPE :REGULAR> 1 2 1 33 64 3 2) [tl,external]
1: (SB-ARM64-ASM::|ubfm| #<SB-ASSEM:SEGMENT :TYPE :REGULAR> #<SB-C::VOP :INFO SB-VM::LDB-C/FIXNUM :ARGS #<SB-C:TN-REF :TN #<SB-C:TN X!1[NL3]> :WRITE-P NIL :VOP SB-VM::LDB-C/FIXNUM> :RESULTS #<SB-C:TN-REF :TN #<SB-C:TN t2[NL2]> :WRITE-P T :VOP SB-VM::LDB-C/FIXNUM> :CODEGEN-INFO (32 32)> #<SB-C:TN t2[NL2]> #<SB-C:TN X!1[NL3]> 33 64)
2: ((SB-C::VOP SB-VM::LDB-C/FIXNUM) #<SB-C::VOP :INFO SB-VM::LDB-C/FIXNUM :ARGS #<SB-C:TN-REF :TN #<SB-C:TN X!1[NL3]> :WRITE-P NIL :VOP SB-VM::LDB-C/FIXNUM> :RESULTS #<SB-C:TN-REF :TN #<SB-C:TN t2[NL2]> :WRITE-P T :VOP SB-VM::LDB-C/FIXNUM> :CODEGEN-INFO (32 32)>)
3: (SB-C::GENERATE-CODE #<SB-C:COMPONENT :NAME SKEIN-INCREMENT-COUNTER {1006D91BD3}>)
4: (SB-C::%COMPILE-COMPONENT #<SB-C:COMPONENT :NAME SKEIN-INCREMENT-COUNTER {1006D91BD3}>)
5: (SB-C::COMPILE-COMPONENT #<SB-C:COMPONENT :NAME SKEIN-INCREMENT-COUNTER {1006D91BD3}>)
6: (SB-C::%COMPILE (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY (UNSIGNED-BYTE 64) (2)) TWEAK) (TYPE (UNSIGNED-BYTE 32) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (BLOCK SKEIN-INCREMENT-COUNTER (LET ((X #) (Y #) (Z #)) (DECLARE (TYPE # X Y Z)) (SETF X (MOD64+ X N) Y (MOD64+ Y #) Z (MOD64+ Z #)) (SETF (LDB # #) (LDB # X) (LDB # #) (LDB # Y)) (SETF (LDB # #) (LDB # Z)) (VALUES)))) #<SB-FASL:FASL-OUTPUT "/home/myon/.cache/common-lisp/sbcl-1.3.11.debian-linux-arm64/home/myon/pgloader/ironclad/src/digests/skein-tmp2K9J0HSR.fasl"> :NAME NIL :PATH ((FUNCTION #1=(SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE # TWEAK) (TYPE # N) (OPTIMIZE # # # # #)) (BLOCK SKEIN-INCREMENT-COUNTER (LET # # # # # #)))) #1# #2=(SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) #1# (SB-C:SOURCE-LOCATION)) #2# (PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) #2#) SB-C::ORIGINAL-SOURCE-START 0 26))
7: (SB-C::FOPCOMPILE-FUNCTION #<SB-FASL:FASL-OUTPUT "/home/myon/.cache/common-lisp/sbcl-1.3.11.debian-linux-arm64/home/myon/pgloader/ironclad/src/digests/skein-tmp2K9J0HSR.fasl"> (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY (UNSIGNED-BYTE 64) (2)) TWEAK) (TYPE (UNSIGNED-BYTE 32) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (BLOCK SKEIN-INCREMENT-COUNTER (LET ((X #) (Y #) (Z #)) (DECLARE (TYPE # X Y Z)) (SETF X (MOD64+ X N) Y (MOD64+ Y #) Z (MOD64+ Z #)) (SETF (LDB # #) (LDB # X) (LDB # #) (LDB # Y)) (SETF (LDB # #) (LDB # Z)) (VALUES)))) ((FUNCTION #1=(SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE # TWEAK) (TYPE # N) (OPTIMIZE # # # # #)) (BLOCK SKEIN-INCREMENT-COUNTER (LET # # # # # #)))) #1# #2=(SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) #1# (SB-C:SOURCE-LOCATION)) #2# (PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) #2#) SB-C::ORIGINAL-SOURCE-START 0 26) T)
8: (SB-C::FOPCOMPILE (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY # #) TWEAK) (TYPE (UNSIGNED-BYTE 32) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (BLOCK SKEIN-INCREMENT-COUNTER (LET (# # #) (DECLARE #) (SETF X # Y # Z #) (SETF # # # #) (SETF # #) (VALUES)))) (SB-C:SOURCE-LOCATION)) (#1=(SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE # TWEAK) (TYPE # N) (OPTIMIZE # # # # #)) (BLOCK SKEIN-INCREMENT-COUNTER (LET # # # # # #))) (SB-C:SOURCE-LOCATION)) (PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) #1#) SB-C::ORIGINAL-SOURCE-START 0 26) NIL NIL)
9: (SB-C::CONVERT-AND-MAYBE-COMPILE (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY # #) TWEAK) (TYPE (UNSIGNED-BYTE 32) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (BLOCK SKEIN-INCREMENT-COUNTER (LET (# # #) (DECLARE #) (SETF X # Y # Z #) (SETF # # # #) (SETF # #) (VALUES)))) (SB-C:SOURCE-LOCATION)) (#1=(SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE # TWEAK) (TYPE # N) (OPTIMIZE # # # # #)) (BLOCK SKEIN-INCREMENT-COUNTER (LET # # # # # #))) (SB-C:SOURCE-LOCATION)) (PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) #1#) SB-C::ORIGINAL-SOURCE-START 0 26) NIL)
10: ((FLET SB-C::DEFAULT-PROCESSOR :IN SB-C::PROCESS-TOPLEVEL-FORM) (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY # #) TWEAK) (TYPE (UNSIGNED-BYTE 32) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (BLOCK SKEIN-INCREMENT-COUNTER (LET (# # #) (DECLARE #) (SETF X # Y # Z #) (SETF # # # #) (SETF # #) (VALUES)))) (SB-C:SOURCE-LOCATION)))
11: (SB-C::PROCESS-TOPLEVEL-FORM (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY # #) TWEAK) (TYPE (UNSIGNED-BYTE 32) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (BLOCK SKEIN-INCREMENT-COUNTER (LET (# # #) (DECLARE #) (SETF X # Y # Z #) (SETF # # # #) (SETF # #) (VALUES)))) (SB-C:SOURCE-LOCATION)) ((PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE # # #) (BLOCK SKEIN-INCREMENT-COUNTER #)) (SB-C:SOURCE-LOCATION))) SB-C::ORIGINAL-SOURCE-START 0 26) NIL)
12: (SB-C::PROCESS-TOPLEVEL-PROGN ((EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE # TWEAK) (TYPE # N) (OPTIMIZE # # # # #)) (BLOCK SKEIN-INCREMENT-COUNTER (LET # # # # # #))) (SB-C:SOURCE-LOCATION))) ((PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE # # #) (BLOCK SKEIN-INCREMENT-COUNTER #)) (SB-C:SOURCE-LOCATION))) SB-C::ORIGINAL-SOURCE-START 0 26) NIL)
13: (SB-C::PROCESS-TOPLEVEL-FORM (PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) NIL T)) (SB-IMPL::%DEFUN (QUOTE SKEIN-INCREMENT-COUNTER) (SB-INT:NAMED-LAMBDA SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE # TWEAK) (TYPE # N) (OPTIMIZE # # # # #)) (BLOCK SKEIN-INCREMENT-COUNTER (LET # # # # # #))) (SB-C:SOURCE-LOCATION))) (SB-C::ORIGINAL-SOURCE-START 0 26) NIL)
14: ((FLET SB-C::DEFAULT-PROCESSOR :IN SB-C::PROCESS-TOPLEVEL-FORM) (DEFUN SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY (UNSIGNED-BYTE 64) (2)) TWEAK) (TYPE (UNSIGNED-BYTE 32) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (LET ((X (LDB # #)) (Y (LDB # #)) (Z (LDB # #))) (DECLARE (TYPE (UNSIGNED-BYTE 64) X Y Z)) (SETF X (MOD64+ X N) Y (MOD64+ Y (LDB # X)) Z (MOD64+ Z (LDB # Y))) (SETF (LDB (BYTE 32 0) (AREF TWEAK 0)) (LDB (BYTE 32 0) X) (LDB (BYTE 32 32) (AREF TWEAK 0)) (LDB (BYTE 32 0) Y)) (SETF (LDB (BYTE 32 0) (AREF TWEAK 1)) (LDB (BYTE 32 0) Z)) (VALUES))))
15: (SB-C::PROCESS-TOPLEVEL-FORM (DEFUN SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY (UNSIGNED-BYTE 64) (2)) TWEAK) (TYPE (UNSIGNED-BYTE 32) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (LET ((X (LDB # #)) (Y (LDB # #)) (Z (LDB # #))) (DECLARE (TYPE (UNSIGNED-BYTE 64) X Y Z)) (SETF X (MOD64+ X N) Y (MOD64+ Y (LDB # X)) Z (MOD64+ Z (LDB # Y))) (SETF (LDB (BYTE 32 0) (AREF TWEAK 0)) (LDB (BYTE 32 0) X) (LDB (BYTE 32 32) (AREF TWEAK 0)) (LDB (BYTE 32 0) Y)) (SETF (LDB (BYTE 32 0) (AREF TWEAK 1)) (LDB (BYTE 32 0) Z)) (VALUES))) (SB-C::ORIGINAL-SOURCE-START 0 26) NIL)
16: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-C::SUB-SUB-COMPILE-FILE) (DEFUN SKEIN-INCREMENT-COUNTER (TWEAK N) (DECLARE (TYPE (SIMPLE-ARRAY (UNSIGNED-BYTE 64) (2)) TWEAK) (TYPE (UNSIGNED-BYTE 32) N) (OPTIMIZE (SPEED 3) (SAFETY 0) (SPACE 0) (DEBUG 0) (COMPILATION-SPEED 0))) (LET ((X (LDB # #)) (Y (LDB # #)) (Z (LDB # #))) (DECLARE (TYPE (UNSIGNED-BYTE 64) X Y Z)) (SETF X (MOD64+ X N) Y (MOD64+ Y (LDB # X)) Z (MOD64+ Z (LDB # Y))) (SETF (LDB (BYTE 32 0) (AREF TWEAK 0)) (LDB (BYTE 32 0) X) (LDB (BYTE 32 32) (AREF TWEAK 0)) (LDB (BYTE 32 0) Y)) (SETF (LDB (BYTE 32 0) (AREF TWEAK 1)) (LDB (BYTE 32 0) Z)) (VALUES))) :CURRENT-INDEX 26)
17: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-C::SUB-SUB-COMPILE-FILE) {100250A58B}> #<SB-C::SOURCE-INFO {1006C5F403}> SB-C::INPUT-ERROR-IN-COMPILE-FILE)
18: (SB-C::SUB-SUB-COMPILE-FILE #<SB-C::SOURCE-INFO {1006C5F403}>)
19: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-C::SUB-COMPILE-FILE))
20: ((FLET #:WITHOUT-INTERRUPTS-BODY-375 :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
21: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-C::SUB-COMPILE-FILE) {7F7D334ABB}> #<SB-THREAD:MUTEX "World Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {10030982A3}>> T NIL)
22: ((LAMBDA NIL :IN SB-C::SUB-COMPILE-FILE))
23: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
24: (SB-C::SUB-COMPILE-FILE #<SB-C::SOURCE-INFO {1006C5F403}>)
25: (COMPILE-FILE #P"/home/myon/pgloader/ironclad/src/digests/skein.lisp" :OUTPUT-FILE #P"/home/myon/.cache/common-lisp/sbcl-1.3.11.debian-linux-arm64/home/myon/pgloader/ironclad/src/digests/skein-tmp2K9J0HSR.fasl" :VERBOSE NIL :PRINT NIL :EXTERNAL-FORMAT :UTF-8 :TRACE-FILE NIL :BLOCK-COMPILE NIL :EMIT-CFASL NIL)
26: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<CLOSURE (LAMBDA NIL :IN UIOP/LISP-BUILD:COMPILE-FILE*) {1006C5CF1B}> NIL)
27: (UIOP/PATHNAME:CALL-WITH-ENOUGH-PATHNAME #P"/home/myon/pgloader/ironclad/src/digests/skein.lisp" NIL #<CLOSURE (LAMBDA (UIOP/LISP-BUILD::INPUT-FILE) :IN UIOP/LISP-BUILD:COMPILE-FILE*) {1006C5CE9B}>)
28: (UIOP/LISP-BUILD:COMPILE-FILE* #P"/home/myon/pgloader/ironclad/src/digests/skein.lisp" :OUTPUT-FILE #P"/home/myon/.cache/common-lisp/sbcl-1.3.11.debian-linux-arm64/home/myon/pgloader/ironclad/src/digests/skein.fasl" :EXTERNAL-FORMAT :UTF-8 :WARNINGS-FILE NIL)
29: (ASDF/LISP-ACTION:PERFORM-LISP-COMPILATION #<ASDF/LISP-ACTION:COMPILE-OP > #<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE "ironclad" "src" "digests" "skein">)
30: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unavailable argument> #<unavailable argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE "ironclad" "src" "digests" "skein">)
31: ((:METHOD ASDF/ACTION:PERFORM :AROUND (ASDF/LISP-ACTION:COMPILE-OP IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE)) #<ASDF/LISP-ACTION:COMPILE-OP > #<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE "ironclad" "src" "digests" "skein">) [fast-method]
32: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE "ironclad" "src" "digests" "skein">) [fast-method]
33: ((:METHOD ASDF/PLAN:PERFORM-PLAN (LIST)) ((#1=#<ASDF/LISP-ACTION:PREPARE-OP > . #2=#<ASDF/OPERATE:REQUIRE-SYSTEM "sb-rotate-byte">) (#3=#<ASDF/LISP-ACTION:COMPILE-OP > . #2#) (#4=#<ASDF/LISP-ACTION:LOAD-OP > . #2#) (#1# . #5=#<ASDF/OPERATE:REQUIRE-SYSTEM "sb-posix">) (#3# . #5#) (#4# . #5#) (#1# . #<ASDF/SYSTEM:SYSTEM #6="nibbles">) (#1# . #7=#<ASDF/COMPONENT:STATIC-FILE #6# "README">) (#3# . #7#) (#4# . #7#) (#1# . #8=#<ASDF/COMPONENT:STATIC-FILE #6# "LICENSE">) (#3# . #8#) ...) :FORCE NIL) [fast-method]
34: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
35: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) ((#1=#<ASDF/LISP-ACTION:PREPARE-OP > . #2=#<ASDF/OPERATE:REQUIRE-SYSTEM "sb-rotate-byte">) (#3=#<ASDF/LISP-ACTION:COMPILE-OP > . #2#) (#4=#<ASDF/LISP-ACTION:LOAD-OP > . #2#) (#1# . #5=#<ASDF/OPERATE:REQUIRE-SYSTEM "sb-posix">) (#3# . #5#) (#4# . #5#) (#1# . #<ASDF/SYSTEM:SYSTEM #6="nibbles">) (#1# . #7=#<ASDF/COMPONENT:STATIC-FILE #6# "README">) (#3# . #7#) (#4# . #7#) (#1# . #8=#<ASDF/COMPONENT:STATIC-FILE #6# "LICENSE">) (#3# . #8#) ...)) [fast-method]
36: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
37: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {100308F3F3}>) [fast-method]
38: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "ironclad">) [fast-method]
39: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "ironclad">)
40: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
41: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "ironclad">) [fast-method]
42: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP :IRONCLAD)
43: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
44: (ASDF/CACHE:CALL-WITH-ASDF-CACHE #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {100308A51B}> :OVERRIDE NIL :KEY NIL)
45: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :IRONCLAD) [fast-method]
46: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :IRONCLAD) [fast-method]
47: (ASDF/OPERATE:LOAD-SYSTEM :IRONCLAD)
48: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/OPERATE:LOAD-SYSTEM :IRONCLAD) #<NULL-LEXENV>)
49: (EVAL (ASDF/OPERATE:LOAD-SYSTEM :IRONCLAD))
50: (SB-EXT:INTERACTIVE-EVAL (ASDF/OPERATE:LOAD-SYSTEM :IRONCLAD) :EVAL NIL)
51: (SB-IMPL::REPL-FUN NIL)
52: ((LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL))
53: (SB-IMPL::%WITH-REBOUND-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL) {10030861FB}>)
54: (SB-IMPL::TOPLEVEL-REPL NIL)
55: (SB-IMPL::TOPLEVEL-INIT)
56: ((FLET #:WITHOUT-INTERRUPTS-BODY-86 :IN SB-EXT:SAVE-LISP-AND-DIE))
57: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))
```

**Comment by stassats** [comment]
That's an SBCL bug, would be fixed tomorrow.
(And I should express my slight disappointment in the fact that this was reported here and not in any of the SBCL channels, where it would have been dealt with much quicker)

**Comment by stassats** [comment]
Fixed now.
